import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FontAwesomeConfig from "@/fontawesome";
import Sidebar from "./components/SideBar";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CLE IN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      

<div className="flex h-screen">
      <Sidebar />
      <div className="flex-1 flex flex-col">
        <Navbar title="Dashboard" />
        <div className="flex-1 overflow-auto">
          {children}
        </div>
      </div>
    </div>

      
         
        
       
      </body>
    </html>
  );
}
